/*
 * This source file was generated by the Gradle 'init' task
 */
package prog2.ex3;

public class App {


    public static void main(String[] args){
        Dice dice = new Dice();
        System.out.println(dice.getValue());
    }
}
